(function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};g.Symbol||(g.Symbol=ba)}var da=0;function ba(a){return"jscomp_symbol_"+(a||"")+da++}
function l(){k();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return ea(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ea(a){l();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}function n(a){l();k();l();var b=a[Symbol.iterator];return b?b.call(a):m(a)}
function p(a){if(!(a instanceof Array)){a=n(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function fa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}var q=window.Element.prototype,r=q.matches||q.matchesSelector||q.webkitMatchesSelector||q.mozMatchesSelector||q.msMatchesSelector||q.oMatchesSelector;
function ha(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||ia(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||ia(a,d))return!0}return!1}function ia(a,b){if("string"!=typeof b)return!1;if(r)return r.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}function ja(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function ka(a,b,c){function d(a){var d;if(h.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),f=0,C;C=e[f];f++)1==C.nodeType&&ha(C,b)&&(d=C);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(ja(d)),e=0;f=d[e];e++)if(ha(f,b)){d=f;break a}d=void 0}d&&c.call(d,a,d)}var e=document,h={composed:!0,B:!0},h=void 0===h?{}:h;e.addEventListener(a,d,h.B);return{j:function(){e.removeEventListener(a,d,h.B)}}}
function la(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var ma=/:(80|443)$/,t=document.createElement("a"),u={};
function v(a){a=a&&"."!=a?a:location.href;if(u[a])return u[a];t.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return v(t.href);var b="80"==t.port||"443"==t.port?"":t.port,b="0"==b?"":b,c=t.host.replace(ma,"");return u[a]={hash:t.hash,host:c,hostname:t.hostname,href:t.href,origin:t.origin?t.origin:t.protocol+"//"+c,pathname:"/"==t.pathname.charAt(0)?t.pathname:"/"+t.pathname,port:b,protocol:t.protocol,search:t.search}}var w=[];
function na(a,b){var c=this;this.context=a;this.v=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.b=[];this.a=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.a[c.a.length-1].apply(null,[].concat(p(b)))};this.c?a.set(b,this.g):a[b]=this.g}function x(a,b,c){a=oa(a,b);a.b.push(c);pa(a)}function y(a,b,c){a=oa(a,b);c=a.b.indexOf(c);-1<c&&(a.b.splice(c,1),0<a.b.length?pa(a):a.j())}
function pa(a){a.a=[];for(var b,c=0;b=a.b[c];c++){var d=a.a[c-1]||a.f.bind(a.context);a.a.push(b(d))}}na.prototype.j=function(){var a=w.indexOf(this);-1<a&&(w.splice(a,1),this.c?this.context.set(this.v,this.f):this.context[this.v]=this.f)};function oa(a,b){var c=w.filter(function(c){return c.context==a&&c.v==b})[0];c||(c=new na(a,b),w.push(c));return c}
function z(a,b,c,d,e,h){if("function"==typeof d){var f=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e,h);f(c)}}}return A({},a,b)}function qa(a,b){var c=la(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=ra(a.slice(b.length));d[a]=e}});return d}
function sa(a){var b;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];clearTimeout(b);b=setTimeout(function(){return a.apply(null,[].concat(p(d)))},500)}}function ta(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var B={};
function ua(a,b){function c(){clearTimeout(e.timeout);e.send&&y(a,"send",e.send);delete B[d];e.A.forEach(function(a){return a()})}var d=a.get("trackingId"),e=B[d]=B[d]||{};clearTimeout(e.timeout);e.timeout=setTimeout(c,0);e.A=e.A||[];e.A.push(b);e.send||(e.send=function(a){return function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c();a.apply(null,[].concat(p(d)))}},x(a,"send",e.send))}
var A=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,e=c.length;d<e;d++){var h=Object(c[d]),f;for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(a[f]=h[f])}return a};function ra(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}var D=function va(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,va)};
function E(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var F={C:1,J:2,K:3,L:4,M:5,F:6,G:7,N:8,O:9,D:10},G=Object.keys(F).length;
function H(a,b){a.set("\x26_av","2.4.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<G)for(var d=G-c.length;d;)c="0"+c,d--;b=G-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}function I(a,b){H(a,F.C);this.a=A({},b);this.g=a;this.b=this.a.stripQuery&&this.a.queryDimensionIndex?"dimension"+this.a.queryDimensionIndex:null;this.f=this.f.bind(this);this.c=this.c.bind(this);x(a,"get",this.f);x(a,"buildHitTask",this.c)}
I.prototype.f=function(a){var b=this;return function(c){if("page"==c||c==b.b){var d={location:a("location"),page:a("page")};return wa(b,d)[c]}return a(c)}};I.prototype.c=function(a){var b=this;return function(c){var d=wa(b,{location:c.get("location"),page:c.get("page")});c.set(d,null,!0);a(c)}};
function wa(a,b){var c=v(b.page||b.location),d=c.pathname;if(a.a.indexFilename){var e=d.split("/");a.a.indexFilename==e[e.length-1]&&(e[e.length-1]="",d=e.join("/"))}"remove"==a.a.trailingSlash?d=d.replace(/\/+$/,""):"add"==a.a.trailingSlash&&(/\.\w+$/.test(d)||"/"==d.substr(-1)||(d+="/"));d={page:d+(a.a.stripQuery?xa(a,c.search):c.search)};b.location&&(d.location=b.location);a.b&&(d[a.b]=c.search.slice(1)||"(not set)");return"function"==typeof a.a.urlFieldsFilter?(b=a.a.urlFieldsFilter(d,v),c={page:b.page,
location:b.location},a.b&&(c[a.b]=b[a.b]),c):d}function xa(a,b){if(Array.isArray(a.a.queryParamsWhitelist)){var c=[];b.slice(1).split("\x26").forEach(function(b){var d=n(b.split("\x3d"));b=d.next().value;d=d.next().value;-1<a.a.queryParamsWhitelist.indexOf(b)&&d&&c.push([b,d])});return c.length?"?"+c.map(function(a){return a.join("\x3d")}).join("\x26"):""}return""}I.prototype.remove=function(){y(this.g,"get",this.f);y(this.g,"buildHitTask",this.c)};E("cleanUrlTracker",I);function ya(){this.a={}}
function za(a,b){(a.a.externalSet=a.a.externalSet||[]).push(b)}ya.prototype.H=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(p(c)))})};var J={},K=!1,L;function M(a,b){b=void 0===b?{}:b;this.a={};this.b=a;this.m=b;this.h=null}fa(M,ya);function N(a,b,c){a=["autotrack",a,b].join(":");J[a]||(J[a]=new M(a,c),K||(window.addEventListener("storage",Aa),K=!0));return J[a]}
function O(){if(null!=L)return L;try{window.localStorage.setItem("autotrack","autotrack"),window.localStorage.removeItem("autotrack"),L=!0}catch(a){L=!1}return L}M.prototype.get=function(){if(this.h)return this.h;if(O())try{this.h=P(window.localStorage.getItem(this.b))}catch(a){}return this.h=A({},this.m,this.h)};M.prototype.set=function(a){this.h=A({},this.m,this.h,a);if(O())try{var b=JSON.stringify(this.h);window.localStorage.setItem(this.b,b)}catch(c){}};
function Q(a){a.h={};if(O())try{window.localStorage.removeItem(a.b)}catch(b){}}M.prototype.j=function(){delete J[this.b];Object.keys(J).length||(window.removeEventListener("storage",Aa),K=!1)};function Aa(a){var b=J[a.key];if(b){var c=A({},b.m,P(a.oldValue));a=A({},b.m,P(a.newValue));b.h=a;b.H("externalSet",a,c)}}function P(a){var b={};if(a)try{b=JSON.parse(a)}catch(c){}return b}var R={};
function S(a,b,c){this.f=a;this.timeout=b||T;this.timeZone=c;this.b=this.b.bind(this);x(a,"sendHitTask",this.b);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=N(a.get("trackingId"),"session",{hitTime:0,isExpired:!1});this.a.get().id||this.a.set({id:D()})}function Ba(a,b,c){var d=a.get("trackingId");return R[d]?R[d]:R[d]=new S(a,b,c)}function U(a){return a.a.get().id}
S.prototype.isExpired=function(a){a=void 0===a?U(this):a;if(a!=U(this))return!0;a=this.a.get();if(a.isExpired)return!0;var b=a.hitTime;return b&&(a=new Date,b=new Date(b),a-b>6E4*this.timeout||this.c&&this.c.format(a)!=this.c.format(b))?!0:!1};S.prototype.b=function(a){var b=this;return function(c){a(c);var d=c.get("sessionControl");c="start"==d||b.isExpired();var d="end"==d,e=b.a.get();e.hitTime=+new Date;c&&(e.isExpired=!1,e.id=D());d&&(e.isExpired=!0);b.a.set(e)}};
S.prototype.j=function(){y(this.f,"sendHitTask",this.b);this.a.j();delete R[this.f.get("trackingId")]};var T=30;function V(a,b){H(a,F.D);window.addEventListener&&(this.b=A({increaseThreshold:20,sessionTimeout:T,fieldsObj:{}},b),this.f=a,this.c=Ca(this),this.g=sa(this.g.bind(this)),this.l=this.l.bind(this),this.a=N(a.get("trackingId"),"plugins/max-scroll-tracker"),this.i=Ba(a,this.b.sessionTimeout,this.b.timeZone),x(a,"set",this.l),Da(this))}
function Da(a){100>(a.a.get()[a.c]||0)&&window.addEventListener("scroll",a.g)}
V.prototype.g=function(){var a=document.documentElement,b=document.body,a=Math.min(100,Math.max(0,Math.round(window.pageYOffset/(Math.max(a.offsetHeight,a.scrollHeight,b.offsetHeight,b.scrollHeight)-window.innerHeight)*100))),b=U(this.i);b!=this.a.get().sessionId&&(Q(this.a),this.a.set({sessionId:b}));if(this.i.isExpired(this.a.get().sessionId))Q(this.a);else if(b=this.a.get()[this.c]||0,a>b&&(100!=a&&100!=b||window.removeEventListener("scroll",this.g),b=a-b,100==a||b>=this.b.increaseThreshold)){var c=
{};this.a.set((c[this.c]=a,c.sessionId=U(this.i),c));a={transport:"beacon",eventCategory:"Max Scroll",eventAction:"increase",eventValue:b,eventLabel:String(a),nonInteraction:!0};this.b.maxScrollMetricIndex&&(a["metric"+this.b.maxScrollMetricIndex]=b);this.f.send("event",z(a,this.b.fieldsObj,this.f,this.b.hitFilter))}};V.prototype.l=function(a){var b=this;return function(c,d){a(c,d);var e={};("object"==typeof c&&null!==c?c:(e[c]=d,e)).page&&(c=b.c,b.c=Ca(b),b.c!=c&&Da(b))}};
function Ca(a){a=v(a.f.get("page")||a.f.get("location"));return a.pathname+a.search}V.prototype.remove=function(){this.i.j();window.removeEventListener("scroll",this.g);y(this.f,"set",this.l)};E("maxScrollTracker",V);
function W(a,b){var c=this;H(a,F.F);window.addEventListener&&(this.a=A({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.b=a,this.f=this.f.bind(this),this.c={},this.a.events.forEach(function(a){c.c[a]=ka(a,c.a.linkSelector,c.f)}))}
W.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackOutboundLink(b,v)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),e=v(d),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:e.href},h=A({},this.a.fieldsObj,qa(b,this.a.attributePrefix)),f=z(e,h,this.b,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.b.send("event",f);else{var ca=function(){window.removeEventListener("click",
ca);if(!a.defaultPrevented){a.preventDefault();var b=f.hitCallback;f.hitCallback=ta(function(){"function"==typeof b&&b();location.href=d})}c.b.send("event",f)};window.addEventListener("click",ca)}}};W.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};W.prototype.remove=function(){var a=this;Object.keys(this.c).forEach(function(b){a.c[b].j()})};E("outboundLinkTracker",W);
var X=D();
function Y(a,b){var c=this;H(a,F.G);document.visibilityState&&(this.a=A({sessionTimeout:T,visibleThreshold:5E3,sendInitialPageview:!1,fieldsObj:{}},b),this.b=a,this.i=document.visibilityState,this.s=null,this.w=!1,this.l=this.l.bind(this),this.f=this.f.bind(this),this.o=this.o.bind(this),this.u=this.u.bind(this),this.c=N(a.get("trackingId"),"plugins/page-visibility-tracker"),za(this.c,this.u),this.g=Ba(a,this.a.sessionTimeout,this.a.timeZone),x(a,"set",this.l),window.addEventListener("unload",this.o),
document.addEventListener("visibilitychange",this.f),ua(this.b,function(){if("visible"==document.visibilityState)c.a.sendInitialPageview&&(Z(c,{I:!0}),c.w=!0),c.c.set({time:+new Date,state:"visible",pageId:X,sessionId:U(c.g)});else if(c.a.sendInitialPageview&&c.a.pageLoadsMetricIndex){var a={},a=(a.transport="beacon",a.eventCategory="Page Visibility",a.eventAction="page load",a.eventLabel="(not set)",a["metric"+c.a.pageLoadsMetricIndex]=1,a.nonInteraction=!0,a);c.b.send("event",z(a,c.a.fieldsObj,
c.b,c.a.hitFilter))}}))}
Y.prototype.f=function(){var a=this;if("visible"==document.visibilityState||"hidden"==document.visibilityState){var b=Ea(this),c={time:+new Date,state:document.visibilityState,pageId:X,sessionId:U(this.g)};"visible"==document.visibilityState&&this.a.sendInitialPageview&&!this.w&&(Z(this),this.w=!0);"hidden"==document.visibilityState&&this.s&&clearTimeout(this.s);this.g.isExpired(b.sessionId)?(Q(this.c),"hidden"==this.i&&"visible"==document.visibilityState&&(clearTimeout(this.s),this.s=setTimeout(function(){a.c.set(c);
Z(a,{hitTime:c.time})},this.a.visibleThreshold))):(b.pageId==X&&"visible"==b.state&&Fa(this,b),this.c.set(c));this.i=document.visibilityState}};function Ea(a){var b=a.c.get();"visible"==a.i&&"hidden"==b.state&&b.pageId!=X&&(b.state="visible",b.pageId=X,a.c.set(b));return b}
function Fa(a,b,c){c=(c?c:{}).hitTime;var d={hitTime:c},d=(d?d:{}).hitTime;(b=b.time?(d||+new Date)-b.time:0)&&b>=a.a.visibleThreshold&&(b=Math.round(b/1E3),d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventValue:b,eventLabel:"(not set)"},c&&(d.queueTime=+new Date-c),a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b),a.b.send("event",z(d,a.a.fieldsObj,a.b,a.a.hitFilter)))}
function Z(a,b){var c=b?b:{};b=c.hitTime;var c=c.I,d={transport:"beacon"};b&&(d.queueTime=+new Date-b);c&&a.a.pageLoadsMetricIndex&&(d["metric"+a.a.pageLoadsMetricIndex]=1);a.b.send("pageview",z(d,a.a.fieldsObj,a.b,a.a.hitFilter))}Y.prototype.l=function(a){var b=this;return function(c,d){var e={},e="object"==typeof c&&null!==c?c:(e[c]=d,e);e.page&&e.page!==b.b.get("page")&&"visible"==b.i&&b.f();a(c,d)}};
Y.prototype.u=function(a,b){a.time!=b.time&&(b.pageId!=X||"visible"!=b.state||this.g.isExpired(b.sessionId)||Fa(this,b,{hitTime:a.time}))};Y.prototype.o=function(){"hidden"!=this.i&&this.f()};Y.prototype.remove=function(){this.c.j();this.g.j();y(this.b,"set",this.l);window.removeEventListener("unload",this.o);document.removeEventListener("visibilitychange",this.f)};E("pageVisibilityTracker",Y);})();
